export const DEMO_DEVICE_ID = 'demo-tag-001';
export const DEFAULT_TELEMETRY_TOPIC = 'hospital/demo/location/device/demo-tag-001';
export const DEFAULT_SIMULATOR_INTERVAL_MS = 1600;

export const DEMO_ROUTE = [
  { floor: 1, x: 0, z: 14.2, status: 'idle', zone: 'Main Lobby', label: 'Lobby staging', waitMs: 1400 },
  { floor: 1, x: -4.8, z: 10.8, status: 'moving', zone: 'Clinical Corridor', label: 'Approach triage corridor', waitMs: 1200 },
  { floor: 1, x: -5.2, z: 7, status: 'moving', zone: 'Clinical Corridor', label: 'Align with triage doorway', waitMs: 900 },
  { floor: 1, x: -5.2, z: 7, status: 'moving', zone: 'Clinical Corridor', label: 'Open triage doors', action: 'door', targetId: 'f1-triage-door', waitMs: 1400 },
  { floor: 1, x: -8.8, z: 7, status: 'moving', zone: 'Triage Station', label: 'Pass through triage doorway', waitMs: 900 },
  { floor: 1, x: -12.4, z: 9.8, status: 'moving', zone: 'Triage Station', label: 'Enter triage room', waitMs: 1200 },
  { floor: 1, x: -13.2, z: 10, status: 'moving', zone: 'Triage Station', label: 'Inspect triage terminal', action: 'objective', targetId: 'triage-terminal', waitMs: 2200 },
  { floor: 1, x: -11.2, z: 11.2, status: 'idle', zone: 'Triage Station', label: 'Talk to head nurse', action: 'npc', targetId: 'head-nurse', waitMs: 2200 },
  { floor: 1, x: -12.2, z: 8.1, status: 'moving', zone: 'Triage Station', label: 'Return to triage doorway', waitMs: 1000 },
  { floor: 1, x: -8.8, z: 7, status: 'moving', zone: 'Triage Station', label: 'Align to exit triage doorway', waitMs: 900 },
  { floor: 1, x: -5.2, z: 7, status: 'moving', zone: 'Clinical Corridor', label: 'Exit to main corridor', waitMs: 1000 },
  { floor: 1, x: -4.8, z: -4.8, status: 'moving', zone: 'Clinical Corridor', label: 'Move toward pharmacy corridor', waitMs: 1200 },
  { floor: 1, x: -5.2, z: -7, status: 'moving', zone: 'Clinical Corridor', label: 'Align with pharmacy doorway', waitMs: 900 },
  { floor: 1, x: -5.2, z: -7, status: 'moving', zone: 'Clinical Corridor', label: 'Open pharmacy doors', action: 'door', targetId: 'f1-pharmacy-door', waitMs: 1400 },
  { floor: 1, x: -8.8, z: -7, status: 'moving', zone: 'Pharmacy Prep', label: 'Pass through pharmacy doorway', waitMs: 900 },
  { floor: 1, x: -12.3, z: -9.4, status: 'moving', zone: 'Pharmacy Prep', label: 'Skirt pharmacy geo-fence boundary', waitMs: 1800 },
  { floor: 1, x: -8.8, z: -7, status: 'moving', zone: 'Pharmacy Prep', label: 'Align to exit pharmacy doorway', waitMs: 900 },
  { floor: 1, x: -5.2, z: -7, status: 'moving', zone: 'Clinical Corridor', label: 'Retreat from pharmacy bay', waitMs: 1000 },
  { floor: 1, x: -2.8, z: 12.2, status: 'moving', zone: 'Main Lobby', label: 'Return to stair corridor', waitMs: 1200 },
  { floor: 1, x: -3.9, z: 12.4, status: 'moving', zone: 'Main Lobby', label: 'Ascend to Floor 2', action: 'stairs', targetId: 'f1-up', waitMs: 1800 },
  { floor: 2, x: 3.4, z: 11.3, status: 'moving', zone: 'Clinical Corridor', label: 'Ward arrival', waitMs: 1200 },
  { floor: 2, x: 5.2, z: 7, status: 'moving', zone: 'Clinical Corridor', label: 'Align with ICU doorway', waitMs: 900 },
  { floor: 2, x: 5.2, z: 7, status: 'moving', zone: 'Clinical Corridor', label: 'Open ICU doors', action: 'door', targetId: 'f2-icu-door', waitMs: 1400 },
  { floor: 2, x: 8.8, z: 7, status: 'moving', zone: 'ICU Monitoring', label: 'Pass through ICU doorway', waitMs: 900 },
  { floor: 2, x: 11.6, z: 12.2, status: 'moving', zone: 'ICU Monitoring', label: 'Arc around ICU center block', waitMs: 900 },
  { floor: 2, x: 14.2, z: 12.4, status: 'moving', zone: 'ICU Monitoring', label: 'Skirt ICU isolation geo-fence', waitMs: 1800 },
  { floor: 2, x: 10.4, z: 10.6, status: 'moving', zone: 'ICU Monitoring', label: 'Inspect ICU monitoring board from safe stand-off point', action: 'objective', targetId: 'icu-board', waitMs: 2200 },
  { floor: 2, x: 8.8, z: 7, status: 'moving', zone: 'ICU Monitoring', label: 'Return to ICU doorway', waitMs: 900 },
  { floor: 2, x: 5.2, z: 7, status: 'moving', zone: 'Clinical Corridor', label: 'Exit ICU doorway', waitMs: 900 },
  { floor: 2, x: 1.2, z: -1, status: 'moving', zone: 'Clinical Corridor', label: 'Cross ward corridor', waitMs: 1200 },
  { floor: 2, x: -2.8, z: -2.8, status: 'idle', zone: 'Clinical Corridor', label: 'Talk to ward doctor', action: 'npc', targetId: 'ward-doctor', waitMs: 2200 },
  { floor: 2, x: -2.9, z: 12.3, status: 'moving', zone: 'Clinical Corridor', label: 'Return to diagnostics stairs', waitMs: 1200 },
  { floor: 2, x: -3.9, z: 12.4, status: 'moving', zone: 'Clinical Corridor', label: 'Ascend to Floor 3', action: 'stairs', targetId: 'f2-up', waitMs: 1800 },
  { floor: 3, x: 3.4, z: 11.3, status: 'moving', zone: 'Clinical Corridor', label: 'Diagnostics arrival', waitMs: 1200 },
  { floor: 3, x: 5.2, z: -7, status: 'moving', zone: 'Clinical Corridor', label: 'Align with archive doorway', waitMs: 900 },
  { floor: 3, x: 5.2, z: -7, status: 'moving', zone: 'Clinical Corridor', label: 'Open archive doors', action: 'door', targetId: 'f3-records-door', waitMs: 1400 },
  { floor: 3, x: 8.8, z: -7, status: 'moving', zone: 'Radiology Records', label: 'Pass through archive doorway', waitMs: 900 },
  { floor: 3, x: 9.6, z: -4.6, status: 'moving', zone: 'Radiology Records', label: 'Skirt archive cabinet edge', waitMs: 900 },
  { floor: 3, x: 14.2, z: -4.6, status: 'moving', zone: 'Radiology Records', label: 'Inspect radiology archive terminal near MRI geo-fence', action: 'objective', targetId: 'radiology-terminal', waitMs: 2400 },
  { floor: 3, x: 9.6, z: -4.6, status: 'moving', zone: 'Radiology Records', label: 'Clear archive cabinet edge', waitMs: 900 },
  { floor: 3, x: 8.8, z: -7, status: 'moving', zone: 'Radiology Records', label: 'Return to archive doorway', waitMs: 900 },
  { floor: 3, x: 5.2, z: -7, status: 'moving', zone: 'Clinical Corridor', label: 'Exit archive doorway', waitMs: 900 },
  { floor: 3, x: 3.2, z: 12.2, status: 'moving', zone: 'Clinical Corridor', label: 'Return to stair corridor', waitMs: 1200 },
  { floor: 3, x: 4, z: 12.4, status: 'moving', zone: 'Clinical Corridor', label: 'Descend to Floor 2', action: 'stairs', targetId: 'f3-down', waitMs: 1800 },
  { floor: 2, x: 3.2, z: 11.3, status: 'moving', zone: 'Clinical Corridor', label: 'Ward return', waitMs: 1200 },
  { floor: 2, x: 4, z: 12.4, status: 'moving', zone: 'Clinical Corridor', label: 'Descend to Floor 1', action: 'stairs', targetId: 'f2-down', waitMs: 1800 },
  { floor: 1, x: 0, z: 12.5, status: 'idle', zone: 'Main Lobby', label: 'Demo loop complete', waitMs: 2600 }
];